services:
  db:
    image: postgres:15  
    container_name: postgres_container_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./data/db:/var/lib/postgresql/data  
    ports:
      - "5432:5432" 

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    user: '$UID:$GID'
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80" 
    depends_on:
      - db
